const exAlunos = [
  {
    codigo: "001",
    apelido: "FORMIGÃO",
    nome: "Jose Daniel Goncalves Vieira",
    curso: "Farmacia",
    turma: "85",
    cidade: "Vitoria",
    estado: "ES",
  },
  {
    codigo: "002",
    apelido: "PDS",
    nome: "Marcelo Tardin Alves",
    curso: "Engenharia Metalurgica",
    turma: "85",
    cidade: "Vitoria",
    estado: "ES",
  },
  {
    codigo: "003",
    apelido: "KAPETA",
    nome: "Aluísio Temponi Leite",
    curso: "Farmacia - Bioquímica",
    turma: "86",
    cidade: "Santa Maria do Suacui",
    estado: "MG",
  },
  {
    codigo: "004",
    apelido: "DEGAS",
    nome: "Cassiano Jose Vieira Neto",
    curso: "Engenharia Civil",
    turma: "86",
    cidade: "Sao Francisco",
    estado: "MG",
  },
  {
    codigo: "005",
    apelido: "PAULÃO",
    nome: "Paulo de Tarso Collares Tavora dos Santos",
    curso: "Farmacia - Bioquímica",
    turma: "86",
    cidade: "Santos",
    estado: "SP",
  },
  {
    codigo: "006",
    apelido: "TULIPA",
    nome: "Servio Tulio Portela",
    curso: "Engenharia Civil",
    turma: "87",
    cidade: "Divinopolis",
    estado: "MG",
  },
  {
    codigo: "007",
    apelido: "COSTELOS",
    nome: "Ivanir Luiz de Oliveira",
    curso: "Engenharia Metalurgica",
    turma: "88",
    cidade: "Barbacena",
    estado: "MG",
  },
  {
    codigo: "008",
    apelido: "BAÚ",
    nome: "Antônio Geraldo Alves",
    curso: "Farmacia - Bioquímica",
    turma: "88",
    cidade: "Ubá",
    estado: "MG",
  },
  {
    codigo: "009",
    apelido: "KOSSADOR",
    nome: "Eder Franco da Silva",
    curso: "Engenharia de Minas",
    turma: "89",
    cidade: "Taquaritinga",
    estado: "SP",
  },
  {
    codigo: "010",
    apelido: "JACÓ",
    nome: "Alisson Barbosa Junior",
    curso: "Farmacia - Bioquímica",
    turma: "89",
    cidade: "Monte Azul",
    estado: "MG",
  },
  {
    codigo: "011",
    apelido: "ESPACIAL",
    nome: "Rilke Novato Publio",
    curso: "Farmacia - Bioquímica",
    turma: "89",
    cidade: "Urandi",
    estado: "BA",
  },
  {
    codigo: "012",
    apelido: "FERNANDIM",
    nome: "Fernando de Melo Krâhenbûhl",
    curso: "Engenharia Geologica",
    turma: "89",
    cidade: "Sao Paulo",
    estado: "SP",
  },
  {
    codigo: "013",
    apelido: "FAFÁ",
    nome: "Rafael Adriano Lopes",
    curso: "Engenharia Metalurgica",
    turma: "89",
    cidade: "Itauna",
    estado: "MG",
  },
  {
    codigo: "014",
    apelido: "AROLDÃO",
    nome: "Halley Marques de Carvalho",
    curso: "Farmacia - Bioquímica",
    turma: "90",
    cidade: "Itauna",
    estado: "MG",
  },
  {
    codigo: "015",
    apelido: "MIRIM",
    nome: "Jose Miro do Prado",
    curso: "Farmacia - Bioquímica",
    turma: "90",
    cidade: "Monte Azul",
    estado: "MG",
  },
  {
    codigo: "016",
    apelido: "TIÃO",
    nome: "Sebastiao Monteiro de Carvalho",
    curso: "Farmacia - Bioquímica",
    turma: "90",
    cidade: "Governador Valadares",
    estado: "MG",
  },
  {
    codigo: "017",
    apelido: "MACARRÃO",
    nome: "Sergio Eustáquio Pereira",
    curso: "Farmácia",
    turma: "",
    cidade: "",
    estado: "",
  },
  {
    codigo: "018",
    apelido: "UGA",
    nome: "Wilson Moreira Quintão",
    curso: "Farmácia - Bioquímica",
    turma: "92",
    cidade: "Timoteo",
    estado: "MG",
  },
  {
    codigo: "019",
    apelido: "HIENA",
    nome: "Hélio Goncalves da Silva",
    curso: "Engenharia Metalúrgica",
    turma: "92",
    cidade: "Itauna",
    estado: "MG",
  },
  {
    codigo: "020",
    apelido: "KUPYN",
    nome: "José Carlos de Melo",
    curso: "Farmácia - Bioquímica",
    turma: "93",
    cidade: "Unaí",
    estado: "MG",
  },
  {
    codigo: "021",
    apelido: "TONIM",
    nome: "Antônio Jose de Matos",
    curso: "Engenharia de Minas",
    turma: "94",
    cidade: "Santa Rita de Ouro Preto",
    estado: "MG",
  },
  {
    codigo: "022",
    apelido: "TUCANO",
    nome: "Jose Goncalves de Paula Neto",
    curso: "Engenharia Metalurgica",
    turma: "94",
    cidade: "Funilândia",
    estado: "MG",
  },
  {
    codigo: "023",
    apelido: "FAÇANHA",
    nome: "Henrique Amaral Coura",
    curso: "Farmacia - Bioquímica",
    turma: "94",
    cidade: "Belo Horizonte",
    estado: "MG",
  },
  {
    codigo: "024",
    apelido: "SONSEIRA",
    nome: "Alessandro Dias Fernandes",
    curso: "Farmacia - Bioquímica",
    turma: "94",
    cidade: "Monte Azul",
    estado: "MG",
  },
  {
    codigo: "025",
    apelido: "RODELA",
    nome: "Flavio de Oliveira",
    curso: "Farmacia - Bioquímica",
    turma: "94/2",
    cidade: "Santa Tereza",
    estado: "ES",
  },
  {
    codigo: "026",
    apelido: "KICHUTE",
    nome: "Emerson Geraldo Soares",
    curso: "Ciência da Computacao",
    turma: "95",
    cidade: "Timoteo",
    estado: "MG",
  },
  {
    codigo: "027",
    apelido: "BAMBY",
    nome: "Alan Costa Sarcinelli Santos",
    curso: "Nutricao",
    turma: "95",
    cidade: "Colatina",
    estado: "ES",
  },
  {
    codigo: "028",
    apelido: "TAMPINHA",
    nome: "Heberth Moglianne Rodrigues Batista",
    curso: "Farmacia - Bioquímica",
    turma: "96",
    cidade: "Monte Azul",
    estado: "MG",
  },
  {
    codigo: "029",
    apelido: "MYMMO",
    nome: "Gustavo Assis Chaves",
    curso: "Ciência da Computacao",
    turma: "96/2",
    cidade: "Caete",
    estado: "MG",
  },
  {
    codigo: "030",
    apelido: "BUIU",
    nome: "Cleber Jose de Oliveira Costa",
    curso: "Engenharia Metalurgica",
    turma: "96",
    cidade: "Sete Lagoas",
    estado: "MG",
  },
  {
    codigo: "031",
    apelido: "CARNEIRO",
    nome: "Weberton Lopes Bello",
    curso: "Engenharia Civil",
    turma: "96",
    cidade: "Caratinga",
    estado: "MG",
  },
  {
    codigo: "032",
    apelido: "JOELHO",
    nome: "Charleston de Lellis Pimenta Dias",
    curso: "Engenharia de Minas",
    turma: "97",
    cidade: "Guanhaes",
    estado: "MG",
  },
  {
    codigo: "033",
    apelido: "PAKITA",
    nome: "Eder Lana de Oliveira",
    curso: "Engenharia Metalurgica",
    turma: "97",
    cidade: "Timoteo",
    estado: "MG",
  },
  {
    codigo: "034",
    apelido: "Q-JYN",
    nome: "Agnaldo de Souza Ângelo",
    curso: "Nutricao",
    turma: "97",
    cidade: "Antônio Pereira",
    estado: "MG",
  },
  {
    codigo: "035",
    apelido: "BIKUDO",
    nome: "Gladstone de Souza Guerra",
    curso: "Engenharia Metalurgica",
    turma: "98/1",
    cidade: "Timoteo",
    estado: "MG",
  },
  {
    codigo: "036",
    apelido: "TAQUARA",
    nome: "Danilo Sanches Rezende Moraes",
    curso: "Ciência da Computacao",
    turma: "99/2",
    cidade: "Caratinga",
    estado: "MG",
  },
  {
    codigo: "037",
    apelido: "MAGUILLA",
    nome: "Vagner Wesley Nogueira",
    curso: "Farmacia - Bioquímica",
    turma: "00/1",
    cidade: "Mortugaba",
    estado: "BA",
  },
  {
    codigo: "038",
    apelido: "XUTERA",
    nome: "Neilson Duarte de Souza",
    curso: "Engenharia Metalurgica",
    turma: "00/1",
    cidade: "Caratinga",
    estado: "MG",
  },
  {
    codigo: "039",
    apelido: "TATTU",
    nome: "Olímpio Ferreira Miranda",
    curso: "Farmacia - Bioquímica",
    turma: "00/2",
    cidade: "Montezuma",
    estado: "MG",
  },
  {
    codigo: "040",
    apelido: "BUSKAPÉ",
    nome: "Delio Antônio de Queiroz",
    curso: "Farmacia Bioquímica",
    turma: "00/2",
    cidade: "Presidente Olegario",
    estado: "MG",
  },
  {
    codigo: "041",
    apelido: "PAUMYTO",
    nome: "Allan Wojcik da Silva",
    curso: "Ciência da Computacao",
    turma: "00/2",
    cidade: "Pirapora",
    estado: "MG",
  },
  {
    codigo: "042",
    apelido: "CHIPÃ-ZÉ",
    nome: "Jeveson Batista dos Santos",
    curso: "Engenharia Metalurgica",
    turma: "01/2",
    cidade: "Coronel Fabriciano",
    estado: "MG",
  },
  {
    codigo: "043",
    apelido: "CURUJYTO",
    nome: "Wagner Chaves de Assis",
    curso: "Farmacia - Bioquímica",
    turma: "01/2",
    cidade: "Caratinga",
    estado: "MG",
  },
  {
    codigo: "044",
    apelido: "DARROSSA",
    nome: "Rogerio Teixeira de Mello",
    curso: "Direito",
    turma: "02/1",
    cidade: "Itumbiara",
    estado: "GO",
  },
  {
    codigo: "045",
    apelido: "SEUBUNEKO",
    nome: "Newton Otávio Rodrigues de Melo Souza",
    curso: "Engenharia Metalúrgica",
    turma: "02/1",
    cidade: "Brasília",
    estado: "DF",
  },
  {
    codigo: "046",
    apelido: "FOSSA",
    nome: "Christian Glenisson Lemos",
    curso: "Engenharia Metalurgica",
    turma: "02/1",
    cidade: "Passos",
    estado: "MG",
  },
  {
    codigo: "047",
    apelido: "DENGUI",
    nome: "Marcelo Martins Pereira",
    curso: "Nutricao",
    turma: "02/1",
    cidade: "Araguari",
    estado: "MG",
  },
  {
    codigo: "048",
    apelido: "RABYNHO",
    nome: "Isaac Karlo da Silva",
    curso: "Letras",
    turma: "02/2",
    cidade: "Divinopolis",
    estado: "MG",
  },
  {
    codigo: "049",
    apelido: "TABELA",
    nome: "Joaquim Carlos de Castro Megre Junior",
    curso: "Direito",
    turma: "03/1",
    cidade: "Uberlândia",
    estado: "MG",
  },
  {
    codigo: "050",
    apelido: "FRAUDÃO",
    nome: "Frederico Augustus Rocha Cunha",
    curso: "Engenharia de Producao",
    turma: "03/2",
    cidade: "Goiânia",
    estado: "GO",
  },
  {
    codigo: "051",
    apelido: "E.T.",
    nome: "Ronaldo Sapi Rossignoli",
    curso: "Farmacia - Bioquímica",
    turma: "03/2",
    cidade: "Varginha",
    estado: "MG",
  },
  {
    codigo: "052",
    apelido: "SAPUDO",
    nome: "Fabiano Mendes Latini Gomes",
    curso: "Engenharia de Producao",
    turma: "04/2",
    cidade: "Santo Antônio do Grama",
    estado: "MG",
  },
  {
    codigo: "053",
    apelido: "SACI",
    nome: "Pablo Peron de Paula",
    curso: "Engenharia de Producao",
    turma: "04/2",
    cidade: "Sao Geraldo",
    estado: "MG",
  },
  {
    codigo: "054",
    apelido: "MARREKU",
    nome: "Kassio Damaso Bueno",
    curso: "Engenharia de Controle e Automação",
    turma: "05/1",
    cidade: "Goiânia",
    estado: "GO",
  },
  {
    codigo: "055",
    apelido: "MARMOTA",
    nome: "Lucas Reis Costa",
    curso: "Ciência da Computação",
    turma: "07/2",
    cidade: "Pedro Leopoldo",
    estado: "MG",
  },
  {
    codigo: "056",
    apelido: "ISKILO",
    nome: "Matheus Damaceno Artur",
    curso: "Engenharia de Controle e Automação",
    turma: "08/1",
    cidade: "Vitória da Conquista",
    estado: "BA",
  },
  {
    codigo: "057",
    apelido: "SARAVAH",
    nome: "Anderson Batista dos Santos",
    curso: "Engenharia Metalúrgica",
    turma: "08/1",
    cidade: "Coronel Fabriciano",
    estado: "MG",
  },
  {
    codigo: "058",
    apelido: "SOLITÁRIA",
    nome: "Welton Pereira Lopes",
    curso: "Direito",
    turma: "09/1",
    cidade: "Divisa Alegre",
    estado: "MG",
  },
  {
    codigo: "059",
    apelido: "K-POTE",
    nome: "Henrique Mamede Pires Ataídes",
    curso: "Direito",
    turma: "09/1",
    cidade: "Cristalina",
    estado: "GO",
  },
  {
    codigo: "060",
    apelido: "RAYO-X",
    nome: "Brício Cunha Fagundes",
    curso: "Química Industrial",
    turma: "09/2",
    cidade: "Teixeira de Freitas",
    estado: "BA",
  },
  {
    codigo: "061",
    apelido: "AMOLLA",
    nome: "Reuber Lana Antoniazzi Junior",
    curso: "Ciências Biológicas",
    turma: "10/1",
    cidade: "Belo Horizonte",
    estado: "MG",
  },
  {
    codigo: "062",
    apelido: "LEGENDADU",
    nome: "Gabriel Guimarães Gomes",
    curso: "Ciências Biológicas",
    turma: "10/1",
    cidade: "Ponte Nova",
    estado: "MG",
  },
  {
    codigo: "063",
    apelido: "POLIXINELU",
    nome: "Fabrício Nepomuceno Bicalho Santos",
    curso: "Educação Física",
    turma: "12/1",
    cidade: "Belo Horizonte",
    estado: "MG",
  },
  {
    codigo: "064",
    apelido: "MYOLO",
    nome: "José Guilherme Mourão Dantas",
    curso: "Engenharia Geológica",
    turma: "12/1",
    cidade: "São João Del Rei",
    estado: "MG",
  },
  {
    codigo: "065",
    apelido: "PAY-MORRÊU",
    nome: "João Herculano Freire Cavalcante",
    curso: "Engenharia Civil",
    turma: "12/1",
    cidade: "Ponte Alta do Bom Jesus",
    estado: "TO",
  },
  {
    codigo: "066",
    apelido: "100-FUNDU",
    nome: "Rodrigo de Lima Parreiras",
    curso: "Engenharia de Produção",
    turma: "12/2",
    cidade: "São Gonçalo",
    estado: "RJ",
  },
  {
    codigo: "067",
    apelido: "E-PATITE",
    nome: "Nicolas Mamede Pires Ataídes",
    curso: "Engenharia Metalúrgica",
    turma: "13/2",
    cidade: "Cristalina",
    estado: "GO",
  },
  {
    codigo: "068",
    apelido: "INDYOTA",
    nome: "Josué Vinícius De Lima",
    curso: "Engenharia Geológica",
    turma: "13/2",
    cidade: "Barão de Cocais",
    estado: "MG",
  },
  {
    codigo: "069",
    apelido: "KARRANCA",
    nome: "Lucas Prazeres de Matos",
    curso: "Engenharia Metalúrgica",
    turma: "14/2",
    cidade: "Ouro Preto",
    estado: "MG",
  },
  {
    codigo: "070",
    apelido: "INODORO",
    nome: "Ítalo Affonso Silva Milagres",
    curso: "Ciência da Computação",
    turma: "15/1",
    cidade: "Belo Horizonte",
    estado: "MG",
  },
  {
    codigo: "071",
    apelido: "KOIZA-LINDA",
    nome: "Philipe Silva Cardoso de Castro",
    curso: "Engenharia de Minas",
    turma: "15/2",
    cidade: "Teófilo Otoni",
    estado: "MG",
  },
  {
    codigo: "072",
    apelido: "PRÓSSIMU",
    nome: "Pedro Henrique Silva Carvalho",
    curso: "Engenharia Ambiental",
    turma: "15/2",
    cidade: "Itaúna",
    estado: "MG",
  },
  {
    codigo: "073",
    apelido: "DEPEND",
    nome: "Eduardo Afonso Dias",
    curso: "Engenharia Civil",
    turma: "15/2",
    cidade: "Ovo D'Ema / Januária",
    estado: "MG",
  },
  {
    codigo: "074",
    apelido: "LOUVA-DEUS",
    nome: "Gabriel Brandão de Lima",
    curso: "Ciência da Computação",
    turma: "20/1",
    cidade: "Nova Lima",
    estado: "MG",
  },
  {
    codigo: "075",
    apelido: "BERIZAL",
    nome: "Matheus da Silva Santos",
    curso: "Engenharia Civil",
    turma: "20/1",
    cidade: "Pitangui",
    estado: "MG",
  },
  {
    codigo: "076",
    apelido: "SYD",
    nome: "Lucas Matheus Magalhães Silva",
    curso: "Engenharia Metalurgica",
    turma: "20/2",
    cidade: "Felixlândia",
    estado: "MG",
  },
  {
    codigo: "077",
    apelido: "MALFEITO",
    nome: "Camilo Vinicius Carnog Gomes",
    curso: "Engenharia Mecânica",
    turma: "21/2",
    cidade: "Janaúba",
    estado: "MG",
  },
  {
    codigo: "078",
    apelido: "MANDRIÃO",
    nome: "João Pedro Siqueira Mendes",
    curso: "Ciência da Computação",
    turma: "21/2",
    cidade: "Vitória",
    estado: "ES",
  },
  {
    codigo: "079",
    apelido: "CEARÁ",
    nome: "Marcos Antonio Sousa Almeida",
    curso: "Engenharia Civil",
    turma: "22/1",
    cidade: "Taiobeiras",
    estado: "MG",
  },
  {
    codigo: "080",
    apelido: "GRAVETO",
    nome: "Ranan Vitor Oliveira de Sá",
    curso: "Engenharia Ambiental",
    turma: "22/1",
    cidade: "Ipatinga",
    estado: "MG",
  },
];
