const homenageados = [
  {
    codigo: "001",
    apelido: "RISADINHA",
    nome: "Patricia Miranda Pardidi",
    curso: "Nutrição",
    turma: "95",
    cidade: "Belo Horizonte",
    estado: "MG",
    republica: "República Doce Mistura",
  },
  {
    codigo: "002",
    apelido: "DANIELA",
    nome: "Daniela Sanches Rezende Moraes",
    curso: "Farmácia - Bioquímica",
    turma: "96",
    cidade: "Caratinga",
    estado: "MG",
    republica: "República Quase Normal",
  },
  {
    codigo: "003",
    apelido: "FAFA",
    nome: "Faroilde Mcartney Lopes Carneiro",
    curso: "Nutrição",
    turma: "96",
    cidade: "Guanambi",
    estado: "BA",
    republica: "República Convento",
  },
  {
    codigo: "004",
    apelido: "KAKU",
    nome: "Andrêz Soares de Oliveira",
    curso: "",
    turma: "",
    cidade: "João Monlevade",
    estado: "MG",
    republica: "Ex-Morador",
  },
  {
    codigo: "005",
    apelido: "MARIA JOSÉ",
    nome: "Maria José da Silva Pinto",
    curso: "Nutrição",
    turma: "96",
    cidade: "Lorena",
    estado: "SP",
    republica: "República Convento",
  },
  {
    codigo: "006",
    apelido: "CRIS",
    nome: "Cristiane Costa Pinheiro",
    curso: "Farmácia - Bioquímica",
    turma: "96",
    cidade: "Belo Horizonte",
    estado: "MG",
    republica: "República Lumiar",
  },
  {
    codigo: "007",
    apelido: "LÔ",
    nome: "Maria Leonor",
    curso: "",
    turma: "",
    cidade: "Ouro Preto",
    estado: "MG",
    republica: "",
  },
  {
    codigo: "008",
    apelido: "RENATO",
    nome: "Renato Lúcio dos Santos",
    curso: "",
    turma: "",
    cidade: "Ouro Preto",
    estado: "MG",
    republica: "",
  },
  {
    codigo: "009",
    apelido: "ROBERTA",
    nome: "Roberta Ribeiro Ferreira",
    curso: "Ciência da Computação",
    turma: "97",
    cidade: "Inhapim",
    estado: "MG",
    republica: "República Bicho do Mato",
  },
  {
    codigo: "010",
    apelido: "ALINE",
    nome: "Aline Luciana Vieira",
    curso: "Farmácia - Bioquímica",
    turma: "98",
    cidade: "Paraopeba",
    estado: "MG",
    republica: "República Lumiar",
  },
  {
    codigo: "011",
    apelido: "SIMONE",
    nome: "Simone Mendes Pedrosa",
    curso: "Nutrição",
    turma: "99/2",
    cidade: "Inhapim",
    estado: "MG",
    republica: "República Bicho do Mato",
  },
  {
    codigo: "012",
    apelido: "LILIANE",
    nome: "Liliane Monteiro de Barros Moura",
    curso: "Nutrição",
    turma: "03/2",
    cidade: "Belo Horizonte",
    estado: "MG",
    republica: "República Bicho do Mato",
  },
  {
    codigo: "013",
    apelido: "JULIA",
    nome: "Julia Moura Nogueira",
    curso: "",
    turma: "",
    cidade: "",
    estado: "",
    republica: "",
  },
  {
    codigo: "014",
    apelido: "FABIANO",
    nome: "Fabiano da Silva Bandeira",
    curso: "",
    turma: "",
    cidade: "",
    estado: "",
    republica: "",
  },
  {
    codigo: "015",
    apelido: "ZÉ-BUNITIN",
    nome: "Atanael Freitas Assunção",
    curso: "Engenharia de Produção",
    turma: "03/2",
    cidade: "Campina Verde",
    estado: "MG",
    republica: "",
  },
  {
    codigo: "016",
    apelido: "DEYSE",
    nome: "Deyselane Ajeje Barbosa",
    curso: "Nutrição",
    turma: "04/2",
    cidade: "Passos",
    estado: "MG",
    republica: "República Feijão com Arroz",
  },
  {
    codigo: "017",
    apelido: "MÃE",
    nome: "Maria Augusta Rodrigues da Anunciação",
    curso: "",
    turma: "",
    cidade: "Ouro Preto",
    estado: "MG",
    republica: "",
  },
  {
    codigo: "018",
    apelido: "REPLAY",
    nome: "Sérgio Pereira de Lima",
    curso: "Engenharia de Produção",
    turma: "04/2",
    cidade: "Patos de Minas",
    estado: "MG",
    republica: "",
  },
  {
    codigo: "019",
    apelido: "MÁRIO",
    nome: "Mário Felipe Neto",
    curso: "Ciências Biológicas",
    turma: "11/2",
    cidade: "Goiânia",
    estado: "GO",
    republica: "",
  },
  {
    codigo: "020",
    apelido: "JOAQUIN",
    nome: "Joaquin Maria Alarcon de Lastra Halcon",
    curso: "Engenharia Industrial",
    turma: "13/1",
    cidade: "Sevilla",
    estado: "Espanha",
    republica: "",
  },
  {
    codigo: "021",
    apelido: "PAU DE ARARA",
    nome: "Pedro Renan Prego de Castro",
    curso: "",
    turma: "",
    cidade: "Cristalina",
    estado: "GO",
    republica: "",
  },
  {
    codigo: "022",
    apelido: "CARMINHA",
    nome: "Maria do Carmo Carlos Angelo",
    curso: "",
    turma: "",
    cidade: "Acaíaca",
    estado: "MG",
    republica: "",
  },
  {
    codigo: "023",
    apelido: "GABI",
    nome: "Gabriela Tavares Aloise",
    curso: "",
    turma: "",
    cidade: "Santos",
    estado: "SP",
    republica: "",
  },
  {
    codigo: "024",
    apelido: "π-XORRA",
    nome: "Thales da Silva Reis",
    curso: "",
    turma: "",
    cidade: "Curvelo",
    estado: "MG",
    republica: "Ex-Morador",
  },
];
