const moradores = [
  {
    codigo: "001",
    apelido: "PROJETO",
    nome: "Gian Luca Souza Calabró",
    curso: "Engenharia Urbana",
    periodo: "18.1",
    cidade: "Contagem",
    estado: "MG",
    email: "gianlucaufop@gmail.com",
    linkedin: "",
    instagram: "gianlcalabro",
  },
  {
    codigo: "002",
    apelido: "MIJOLETA",
    nome: "Matheus Magalhães Machado",
    curso: "Engenharia de Controle e Automação",
    periodo: "19.1",
    cidade: "Volta Redonda",
    estado: "RJ",
    email: "machadomatheusmagalhaes@gmail.com",
    linkedin: "https://www.linkedin.com/in/matheus-magalhaes-machado/",
    instagram: "machadopas",
  },
  {
    codigo: "003",
    apelido: "GROOT",
    nome: "Ryan Henrique Silva Cunha",
    curso: "Nutrição",
    periodo: "21.2",
    cidade: "Santa Luzia",
    estado: "MG",
    email: "ryan.henriquesilvac@gmail.com",
    linkedin: "",
    instagram: "ryhs_pas",
  },
  {
    codigo: "004",
    apelido: "XP",
    nome: "Lázaro Antônio Alves Veloso",
    curso: "Ciência da Computação",
    periodo: "23.1",
    cidade: "Montes Claros",
    estado: "MG",
    email: "lazaroantonio.veloso@gmail.com",
    linkedin: "",
    instagram: "lazaroizy",
  },
  {
    codigo: "005",
    apelido: "1000JARDAS",
    nome: "Leandro Rodrigues Ribeiro Conde Miranda",
    curso: "Engenharia de Minas",
    periodo: "25.1",
    cidade: "Belém",
    estado: "PA",
    email: "ribeiro.leandroconde@gmail.com",
    linkedin: "leandrosirius",
  },
  {
    codigo: "006",
    apelido: "TIRIÇA",
    nome: "Hector de Castro Marinho",
    curso: "Engenharia Mecânica",
    periodo: "25.1",
    cidade: "Belo Horizonte",
    estado: "MG",
    email: "hectorcastro007@gmail.com",
    linkedin: "hector_marinho",
  },
];
