const moradores = [
  {
    codigo: "001",
    apelido: "PROJETO",
    nome: "Jose Daniel Goncalves Vieira",
    curso: "Farmacia",
    periodo: "85",
    cidade: "Vitoria",
    estado: "ES",
  },
  {
    codigo: "002",
    apelido: "MIJOLETA",
    nome: "Marcelo Tardin Alves",
    curso: "Engenharia Metalurgica",
    periodo: "85",
    cidade: "Vitoria",
    estado: "ES",
  },
  {
    codigo: "003",
    apelido: "GROOT",
    nome: "Aluísio Temponi Leite",
    curso: "Farmacia - Bioquímica",
    periodo: "86",
    cidade: "Santa Maria do Suacui",
    estado: "MG",
  },
  {
    codigo: "004",
    apelido: "XP",
    nome: "Cassiano Jose Vieira Neto",
    curso: "Engenharia Civil",
    periodo: "86",
    cidade: "Sao Francisco",
    estado: "MG",
  },
  {
    codigo: "005",
    apelido: "MYU-JARDAS",
    nome: "Paulo de Tarso Collares Tavora dos Santos",
    curso: "Farmacia - Bioquímica",
    periodo: "86",
    cidade: "Santos",
    estado: "SP",
  },
  {
    codigo: "006",
    apelido: "TIRIÇA",
    nome: "Servio Tulio Portela",
    curso: "Engenharia Civil",
    periodo: "87",
    cidade: "Divinopolis",
    estado: "MG",
  },
];
